package uk.co.birchlabs.touhouwalk.global;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

import uk.co.birchlabs.touhouwalk.R;

/**
 * Created by birch on 06/01/2017.
 */

public class MikoDatabase {
    private static final Map<String, Integer> mikobase;

    static {
        mikobase = new TreeMap<>();
        addMiko(
                "alice",
                R.drawable.alice
        );
        addMiko(
                "aya",
                R.drawable.aya
        );
        addMiko(
                "benben",
                R.drawable.benben
        );
        addMiko(
                "chen",
                R.drawable.chen
        );
        addMiko(
                "chirno",
                R.drawable.chirno
        );
        addMiko(
                "daiyousei",
                R.drawable.daiyousei
        );
        addMiko(
                "eirin",
                R.drawable.eirin
        );
        addMiko(
                "fran",
                R.drawable.fran
        );
        addMiko(
                "hatate",
                R.drawable.hatate
        );
        addMiko(
                "hijiri",
                R.drawable.hijiri
        );
        addMiko(
                "hina",
                R.drawable.hina
        );
        addMiko(
                "huto",
                R.drawable.huto
        );
        addMiko(
                "ichirin",
                R.drawable.ichirin
        );
        addMiko(
                "iku",
                R.drawable.iku
        );
        addMiko(
                "kagerou",
                R.drawable.kagerou
        );
        addMiko(
                "kaguya",
                R.drawable.kaguya
        );
        addMiko(
                "kanako",
                R.drawable.kanako
        );
        addMiko(
                "keine",
                R.drawable.keine
        );
        addMiko(
                "keinekimo",
                R.drawable.keinekimo
        );
        addMiko(
                "kisume",
                R.drawable.kisume
        );
        addMiko(
                "koa",
                R.drawable.koa
        );
        addMiko(
                "kogasa",
                R.drawable.kogasa
        );
        addMiko(
                "koishi",
                R.drawable.koishi
        );
        addMiko(
                "kokoro",
                R.drawable.kokoro
        );
        addMiko(
                "komachi",
                R.drawable.komachi
        );
        addMiko(
                "kyoko",
                R.drawable.kyoko
        );
        addMiko(
                "lily_black",
                R.drawable.lily_black
        );
        addMiko(
                "lily_white",
                R.drawable.lily_white
        );
        addMiko(
                "mamizo",
                R.drawable.mamizo
        );
        addMiko(
                "marisa",
                R.drawable.marisa
        );
        addMiko(
                "meirin",
                R.drawable.meirin
        );
        addMiko(
                "melran",
                R.drawable.melran
        );
        addMiko(
                "merancory",
                R.drawable.merancory
        );
        addMiko(
                "miko",
                R.drawable.miko
        );
        addMiko(
                "minoriko",
                R.drawable.minoriko
        );
        addMiko(
                "mistia",
                R.drawable.mistia
        );
        addMiko(
                "moko",
                R.drawable.moko
        );
        addMiko(
                "momiji",
                R.drawable.momiji
        );
        addMiko(
                "murasa",
                R.drawable.murasa
        );
        addMiko(
                "nazu",
                R.drawable.nazu
        );
        addMiko(
                "nitori",
                R.drawable.nitori
        );
        addMiko(
                "nue",
                R.drawable.nue
        );
        addMiko(
                "orin",
                R.drawable.orin
        );
        addMiko(
                "pal",
                R.drawable.pal
        );
        addMiko(
                "patyuri",
                R.drawable.patyuri
        );
        addMiko(
                "raiko",
                R.drawable.raiko
        );
        addMiko(
                "ran",
                R.drawable.ran
        );
        addMiko(
                "reimu",
                R.drawable.reimu
        );
        addMiko(
                "remiria",
                R.drawable.remiria
        );
        addMiko(
                "rety",
                R.drawable.rety
        );
        addMiko(
                "riguru",
                R.drawable.riguru
        );
        addMiko(
                "rinnosuke",
                R.drawable.rinnosuke
        );
        addMiko(
                "ririka",
                R.drawable.ririka
        );
        addMiko(
                "rumia",
                R.drawable.rumia
        );
        addMiko(
                "runasa",
                R.drawable.runasa
        );
        addMiko(
                "sakuya",
                R.drawable.sakuya
        );
        addMiko(
                "sanae",
                R.drawable.sanae
        );
        addMiko(
                "satori",
                R.drawable.satori
        );
        addMiko(
                "seiga",
                R.drawable.seiga
        );
        addMiko(
                "seija",
                R.drawable.seija
        );
        addMiko(
                "sekibanki",
                R.drawable.sekibanki
        );
        addMiko(
                "shannhai",
                R.drawable.shannhai
        );
        addMiko(
                "shinmyoumaru",
                R.drawable.shinmyoumaru
        );
        addMiko(
                "shizuha",
                R.drawable.shizuha
        );
        addMiko(
                "sikieiki",
                R.drawable.sikieiki
        );
        addMiko(
                "suika",
                R.drawable.suika
        );
        addMiko(
                "suwako",
                R.drawable.suwako
        );
        addMiko(
                "tei",
                R.drawable.tei
        );
        addMiko(
                "tenshi",
                R.drawable.tenshi
        );
        addMiko(
                "tojiko",
                R.drawable.tojiko
        );
        addMiko(
                "tojiko2",
                R.drawable.tojiko2
        );
        addMiko(
                "toramaru",
                R.drawable.toramaru
        );
        addMiko(
                "udonge",
                R.drawable.udonge
        );
        addMiko(
                "utsuho",
                R.drawable.utsuho
        );
        addMiko(
                "wakasagi",
                R.drawable.wakasagi
        );
        addMiko(
                "yakumoyukari",
                R.drawable.yakumoyukari
        );
        addMiko(
                "yamame",
                R.drawable.yamame
        );
        addMiko(
                "yatsuhashi",
                R.drawable.yatsuhashi
        );
        addMiko(
                "yoshika",
                R.drawable.yoshika
        );
        addMiko(
                "yoshika2",
                R.drawable.yoshika2
        );
        addMiko(
                "youmu",
                R.drawable.youmu
        );
        addMiko(
                "yuugi",
                R.drawable.yuugi
        );
        addMiko(
                "yuuka",
                R.drawable.yuuka
        );
        addMiko(
                "yuyuko",
                R.drawable.yuyuko
        );
    }

    private static void addMiko(
            String key,
            int resource
    ) {
        mikobase.put(
                key,
                resource
        );
    }

    public static Integer getMiko(String key) {
        return mikobase.get(key);
    }

    public static Set<String> getKeySet() {
        return mikobase.keySet();
    }

    public static String[] getKeys() {
        return mikobase.keySet().toArray(new String[mikobase.keySet().size()]);
    }

    private static final Set<String> defaultEnabledMikos;

    static {
        defaultEnabledMikos = new HashSet<>();
        defaultEnabledMikos.add("youmu");
        defaultEnabledMikos.add("marisa");
        defaultEnabledMikos.add("reimu");
        defaultEnabledMikos.add("aya");
        defaultEnabledMikos.add("alice");
        defaultEnabledMikos.add("sanae");
        defaultEnabledMikos.add("chirno");
    }

    public static boolean isMikoOnByDefault(String key) {
        return defaultEnabledMikos.contains(key);
    }
}
